Repository Recoded-BPRM-Turkey-FEW-2022/react-ecommerce-ninjas-store, pull requests merged in 2022-06, with the labels that each got.

#12 Filters
  src/App.js
  src/components/Appbar.jsx
  src/components/ProductCards.jsx
  src/components/navbar.jsx
  src/index.js
Labels: enhancement

#13 changing fetching products and adding product page components
  package-lock.json
  package.json
  src/App.js
  src/components/Product.js
  src/components/ProductCards.jsx
  src/components/productPage/ImageGrid.js
  src/components/productPage/MainImage.js
  src/components/productPage/ProductDetails.js
  src/components/productPage/ProductReview.js
  src/index.js
Labels: enhancement

#17 Navbar styling
  src/App.js
  src/components/Appbar.jsx
  src/components/ProductCards.jsx
  src/components/navbar.jsx
Labels: documentation

#21 Cart icon moved
  src/App.js
  src/components/Cart.js
  src/components/Navbar.jsx
Labels: documentation

#23 remove button fixes
  src/App.js
  src/components/Cart.js
  src/components/Navbar.jsx
  src/components/ProductCards.jsx
  src/components/ShoppingItem.jsx
Labels: bug, documentation

#26 localizing complete
  src/components/Navbar.jsx
Labels: documentation, enhancement

#28 search by name added
  src/App.js
  src/components/Navbar.jsx
  src/components/Product.js
Labels: bug, documentation, enhancement

#30 Product page styled
  src/App.js
  src/components/Product.js
Labels: documentation
